// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ads/googleads/v11/resources/account_link.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ads.GoogleAds.V11.Resources {

  /// <summary>Holder for reflection information generated from google/ads/googleads/v11/resources/account_link.proto</summary>
  public static partial class AccountLinkReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ads/googleads/v11/resources/account_link.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountLinkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVnb29nbGUvYWRzL2dvb2dsZWFkcy92MTEvcmVzb3VyY2VzL2FjY291bnRf",
            "bGluay5wcm90bxIiZ29vZ2xlLmFkcy5nb29nbGVhZHMudjExLnJlc291cmNl",
            "cxo4Z29vZ2xlL2Fkcy9nb29nbGVhZHMvdjExL2VudW1zL2FjY291bnRfbGlu",
            "a19zdGF0dXMucHJvdG8aOGdvb2dsZS9hZHMvZ29vZ2xlYWRzL3YxMS9lbnVt",
            "cy9saW5rZWRfYWNjb3VudF90eXBlLnByb3RvGjZnb29nbGUvYWRzL2dvb2ds",
            "ZWFkcy92MTEvZW51bXMvbW9iaWxlX2FwcF92ZW5kb3IucHJvdG8aH2dvb2ds",
            "ZS9hcGkvZmllbGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3Vy",
            "Y2UucHJvdG8itwYKC0FjY291bnRMaW5rEkMKDXJlc291cmNlX25hbWUYASAB",
            "KAlCLOBBBfpBJgokZ29vZ2xlYWRzLmdvb2dsZWFwaXMuY29tL0FjY291bnRM",
            "aW5rEiEKD2FjY291bnRfbGlua19pZBgIIAEoA0ID4EEDSAGIAQESVwoGc3Rh",
            "dHVzGAMgASgOMkcuZ29vZ2xlLmFkcy5nb29nbGVhZHMudjExLmVudW1zLkFj",
            "Y291bnRMaW5rU3RhdHVzRW51bS5BY2NvdW50TGlua1N0YXR1cxJaCgR0eXBl",
            "GAQgASgOMkcuZ29vZ2xlLmFkcy5nb29nbGVhZHMudjExLmVudW1zLkxpbmtl",
            "ZEFjY291bnRUeXBlRW51bS5MaW5rZWRBY2NvdW50VHlwZUID4EEDEnIKGXRo",
            "aXJkX3BhcnR5X2FwcF9hbmFseXRpY3MYBSABKAsySC5nb29nbGUuYWRzLmdv",
            "b2dsZWFkcy52MTEucmVzb3VyY2VzLlRoaXJkUGFydHlBcHBBbmFseXRpY3NM",
            "aW5rSWRlbnRpZmllckID4EEFSAASWgoMZGF0YV9wYXJ0bmVyGAYgASgLMj0u",
            "Z29vZ2xlLmFkcy5nb29nbGVhZHMudjExLnJlc291cmNlcy5EYXRhUGFydG5l",
            "ckxpbmtJZGVudGlmaWVyQgPgQQNIABJWCgpnb29nbGVfYWRzGAcgASgLMjsu",
            "Z29vZ2xlLmFkcy5nb29nbGVhZHMudjExLnJlc291cmNlcy5Hb29nbGVBZHNM",
            "aW5rSWRlbnRpZmllckID4EEDSAASWgoMaG90ZWxfY2VudGVyGAkgASgLMj0u",
            "Z29vZ2xlLmFkcy5nb29nbGVhZHMudjExLnJlc291cmNlcy5Ib3RlbENlbnRl",
            "ckxpbmtJZGVudGlmaWVyQgPgQQNIADph6kFeCiRnb29nbGVhZHMuZ29vZ2xl",
            "YXBpcy5jb20vQWNjb3VudExpbmsSNmN1c3RvbWVycy97Y3VzdG9tZXJfaWR9",
            "L2FjY291bnRMaW5rcy97YWNjb3VudF9saW5rX2lkfUIQCg5saW5rZWRfYWNj",
            "b3VudEISChBfYWNjb3VudF9saW5rX2lkIvQBCiRUaGlyZFBhcnR5QXBwQW5h",
            "bHl0aWNzTGlua0lkZW50aWZpZXISKwoZYXBwX2FuYWx5dGljc19wcm92aWRl",
            "cl9pZBgEIAEoA0ID4EEFSACIAQESGAoGYXBwX2lkGAUgASgJQgPgQQVIAYgB",
            "ARJcCgphcHBfdmVuZG9yGAMgASgOMkMuZ29vZ2xlLmFkcy5nb29nbGVhZHMu",
            "djExLmVudW1zLk1vYmlsZUFwcFZlbmRvckVudW0uTW9iaWxlQXBwVmVuZG9y",
            "QgPgQQVCHAoaX2FwcF9hbmFseXRpY3NfcHJvdmlkZXJfaWRCCQoHX2FwcF9p",
            "ZCJSChlEYXRhUGFydG5lckxpbmtJZGVudGlmaWVyEiEKD2RhdGFfcGFydG5l",
            "cl9pZBgBIAEoA0ID4EEFSACIAQFCEgoQX2RhdGFfcGFydG5lcl9pZCI5ChlI",
            "b3RlbENlbnRlckxpbmtJZGVudGlmaWVyEhwKD2hvdGVsX2NlbnRlcl9pZBgB",
            "IAEoA0ID4EEDImgKF0dvb2dsZUFkc0xpbmtJZGVudGlmaWVyEkAKCGN1c3Rv",
            "bWVyGAMgASgJQingQQX6QSMKIWdvb2dsZWFkcy5nb29nbGVhcGlzLmNvbS9D",
            "dXN0b21lckgAiAEBQgsKCV9jdXN0b21lckKCAgomY29tLmdvb2dsZS5hZHMu",
            "Z29vZ2xlYWRzLnYxMS5yZXNvdXJjZXNCEEFjY291bnRMaW5rUHJvdG9QAVpL",
            "Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9hZHMvZ29v",
            "Z2xlYWRzL3YxMS9yZXNvdXJjZXM7cmVzb3VyY2VzogIDR0FBqgIiR29vZ2xl",
            "LkFkcy5Hb29nbGVBZHMuVjExLlJlc291cmNlc8oCIkdvb2dsZVxBZHNcR29v",
            "Z2xlQWRzXFYxMVxSZXNvdXJjZXPqAiZHb29nbGU6OkFkczo6R29vZ2xlQWRz",
            "OjpWMTE6OlJlc291cmNlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusReflection.Descriptor, global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeReflection.Descriptor, global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V11.Resources.AccountLink), global::Google.Ads.GoogleAds.V11.Resources.AccountLink.Parser, new[]{ "ResourceName", "AccountLinkId", "Status", "Type", "ThirdPartyAppAnalytics", "DataPartner", "GoogleAds", "HotelCenter" }, new[]{ "LinkedAccount", "AccountLinkId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier), global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier.Parser, new[]{ "AppAnalyticsProviderId", "AppId", "AppVendor" }, new[]{ "AppAnalyticsProviderId", "AppId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier), global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier.Parser, new[]{ "DataPartnerId" }, new[]{ "DataPartnerId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier), global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier.Parser, new[]{ "HotelCenterId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier), global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier.Parser, new[]{ "Customer" }, new[]{ "Customer" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents the data sharing connection between a Google Ads account and
  /// another account
  /// </summary>
  public sealed partial class AccountLink : pb::IMessage<AccountLink>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountLink> _parser = new pb::MessageParser<AccountLink>(() => new AccountLink());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AccountLink> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V11.Resources.AccountLinkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountLink() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountLink(AccountLink other) : this() {
      _hasBits0 = other._hasBits0;
      resourceName_ = other.resourceName_;
      accountLinkId_ = other.accountLinkId_;
      status_ = other.status_;
      type_ = other.type_;
      switch (other.LinkedAccountCase) {
        case LinkedAccountOneofCase.ThirdPartyAppAnalytics:
          ThirdPartyAppAnalytics = other.ThirdPartyAppAnalytics.Clone();
          break;
        case LinkedAccountOneofCase.DataPartner:
          DataPartner = other.DataPartner.Clone();
          break;
        case LinkedAccountOneofCase.GoogleAds:
          GoogleAds = other.GoogleAds.Clone();
          break;
        case LinkedAccountOneofCase.HotelCenter:
          HotelCenter = other.HotelCenter.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AccountLink Clone() {
      return new AccountLink(this);
    }

    /// <summary>Field number for the "resource_name" field.</summary>
    public const int ResourceNameFieldNumber = 1;
    private string resourceName_ = "";
    /// <summary>
    /// Immutable. Resource name of the account link.
    /// AccountLink resource names have the form:
    /// `customers/{customer_id}/accountLinks/{account_link_id}`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceName {
      get { return resourceName_; }
      set {
        resourceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account_link_id" field.</summary>
    public const int AccountLinkIdFieldNumber = 8;
    private long accountLinkId_;
    /// <summary>
    /// Output only. The ID of the link.
    /// This field is read only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccountLinkId {
      get { if ((_hasBits0 & 1) != 0) { return accountLinkId_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        accountLinkId_ = value;
      }
    }
    /// <summary>Gets whether the "account_link_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAccountLinkId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "account_link_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAccountLinkId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus status_ = global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified;
    /// <summary>
    /// The status of the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType type_ = global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified;
    /// <summary>
    /// Output only. The type of the linked account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "third_party_app_analytics" field.</summary>
    public const int ThirdPartyAppAnalyticsFieldNumber = 5;
    /// <summary>
    /// Immutable. A third party app analytics link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier ThirdPartyAppAnalytics {
      get { return linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics ? (global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier) linkedAccount_ : null; }
      set {
        linkedAccount_ = value;
        linkedAccountCase_ = value == null ? LinkedAccountOneofCase.None : LinkedAccountOneofCase.ThirdPartyAppAnalytics;
      }
    }

    /// <summary>Field number for the "data_partner" field.</summary>
    public const int DataPartnerFieldNumber = 6;
    /// <summary>
    /// Output only. Data partner link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier DataPartner {
      get { return linkedAccountCase_ == LinkedAccountOneofCase.DataPartner ? (global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier) linkedAccount_ : null; }
      set {
        linkedAccount_ = value;
        linkedAccountCase_ = value == null ? LinkedAccountOneofCase.None : LinkedAccountOneofCase.DataPartner;
      }
    }

    /// <summary>Field number for the "google_ads" field.</summary>
    public const int GoogleAdsFieldNumber = 7;
    /// <summary>
    /// Output only. Google Ads link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier GoogleAds {
      get { return linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds ? (global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier) linkedAccount_ : null; }
      set {
        linkedAccount_ = value;
        linkedAccountCase_ = value == null ? LinkedAccountOneofCase.None : LinkedAccountOneofCase.GoogleAds;
      }
    }

    /// <summary>Field number for the "hotel_center" field.</summary>
    public const int HotelCenterFieldNumber = 9;
    /// <summary>
    /// Output only. Hotel link
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier HotelCenter {
      get { return linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter ? (global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier) linkedAccount_ : null; }
      set {
        linkedAccount_ = value;
        linkedAccountCase_ = value == null ? LinkedAccountOneofCase.None : LinkedAccountOneofCase.HotelCenter;
      }
    }

    private object linkedAccount_;
    /// <summary>Enum of possible cases for the "linked_account" oneof.</summary>
    public enum LinkedAccountOneofCase {
      None = 0,
      ThirdPartyAppAnalytics = 5,
      DataPartner = 6,
      GoogleAds = 7,
      HotelCenter = 9,
    }
    private LinkedAccountOneofCase linkedAccountCase_ = LinkedAccountOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LinkedAccountOneofCase LinkedAccountCase {
      get { return linkedAccountCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLinkedAccount() {
      linkedAccountCase_ = LinkedAccountOneofCase.None;
      linkedAccount_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AccountLink);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AccountLink other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceName != other.ResourceName) return false;
      if (AccountLinkId != other.AccountLinkId) return false;
      if (Status != other.Status) return false;
      if (Type != other.Type) return false;
      if (!object.Equals(ThirdPartyAppAnalytics, other.ThirdPartyAppAnalytics)) return false;
      if (!object.Equals(DataPartner, other.DataPartner)) return false;
      if (!object.Equals(GoogleAds, other.GoogleAds)) return false;
      if (!object.Equals(HotelCenter, other.HotelCenter)) return false;
      if (LinkedAccountCase != other.LinkedAccountCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceName.Length != 0) hash ^= ResourceName.GetHashCode();
      if (HasAccountLinkId) hash ^= AccountLinkId.GetHashCode();
      if (Status != global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified) hash ^= Status.GetHashCode();
      if (Type != global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified) hash ^= Type.GetHashCode();
      if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) hash ^= ThirdPartyAppAnalytics.GetHashCode();
      if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) hash ^= DataPartner.GetHashCode();
      if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) hash ^= GoogleAds.GetHashCode();
      if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) hash ^= HotelCenter.GetHashCode();
      hash ^= (int) linkedAccountCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      if (Status != global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (Type != global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) {
        output.WriteRawTag(42);
        output.WriteMessage(ThirdPartyAppAnalytics);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) {
        output.WriteRawTag(50);
        output.WriteMessage(DataPartner);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) {
        output.WriteRawTag(58);
        output.WriteMessage(GoogleAds);
      }
      if (HasAccountLinkId) {
        output.WriteRawTag(64);
        output.WriteInt64(AccountLinkId);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) {
        output.WriteRawTag(74);
        output.WriteMessage(HotelCenter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      if (Status != global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (Type != global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) {
        output.WriteRawTag(42);
        output.WriteMessage(ThirdPartyAppAnalytics);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) {
        output.WriteRawTag(50);
        output.WriteMessage(DataPartner);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) {
        output.WriteRawTag(58);
        output.WriteMessage(GoogleAds);
      }
      if (HasAccountLinkId) {
        output.WriteRawTag(64);
        output.WriteInt64(AccountLinkId);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) {
        output.WriteRawTag(74);
        output.WriteMessage(HotelCenter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResourceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceName);
      }
      if (HasAccountLinkId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountLinkId);
      }
      if (Status != global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Type != global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ThirdPartyAppAnalytics);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataPartner);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GoogleAds);
      }
      if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HotelCenter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AccountLink other) {
      if (other == null) {
        return;
      }
      if (other.ResourceName.Length != 0) {
        ResourceName = other.ResourceName;
      }
      if (other.HasAccountLinkId) {
        AccountLinkId = other.AccountLinkId;
      }
      if (other.Status != global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.Type != global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType.Unspecified) {
        Type = other.Type;
      }
      switch (other.LinkedAccountCase) {
        case LinkedAccountOneofCase.ThirdPartyAppAnalytics:
          if (ThirdPartyAppAnalytics == null) {
            ThirdPartyAppAnalytics = new global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier();
          }
          ThirdPartyAppAnalytics.MergeFrom(other.ThirdPartyAppAnalytics);
          break;
        case LinkedAccountOneofCase.DataPartner:
          if (DataPartner == null) {
            DataPartner = new global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier();
          }
          DataPartner.MergeFrom(other.DataPartner);
          break;
        case LinkedAccountOneofCase.GoogleAds:
          if (GoogleAds == null) {
            GoogleAds = new global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier();
          }
          GoogleAds.MergeFrom(other.GoogleAds);
          break;
        case LinkedAccountOneofCase.HotelCenter:
          if (HotelCenter == null) {
            HotelCenter = new global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier();
          }
          HotelCenter.MergeFrom(other.HotelCenter);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 24: {
            Status = (global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus) input.ReadEnum();
            break;
          }
          case 32: {
            Type = (global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType) input.ReadEnum();
            break;
          }
          case 42: {
            global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) {
              subBuilder.MergeFrom(ThirdPartyAppAnalytics);
            }
            input.ReadMessage(subBuilder);
            ThirdPartyAppAnalytics = subBuilder;
            break;
          }
          case 50: {
            global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) {
              subBuilder.MergeFrom(DataPartner);
            }
            input.ReadMessage(subBuilder);
            DataPartner = subBuilder;
            break;
          }
          case 58: {
            global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) {
              subBuilder.MergeFrom(GoogleAds);
            }
            input.ReadMessage(subBuilder);
            GoogleAds = subBuilder;
            break;
          }
          case 64: {
            AccountLinkId = input.ReadInt64();
            break;
          }
          case 74: {
            global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) {
              subBuilder.MergeFrom(HotelCenter);
            }
            input.ReadMessage(subBuilder);
            HotelCenter = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 24: {
            Status = (global::Google.Ads.GoogleAds.V11.Enums.AccountLinkStatusEnum.Types.AccountLinkStatus) input.ReadEnum();
            break;
          }
          case 32: {
            Type = (global::Google.Ads.GoogleAds.V11.Enums.LinkedAccountTypeEnum.Types.LinkedAccountType) input.ReadEnum();
            break;
          }
          case 42: {
            global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.ThirdPartyAppAnalyticsLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.ThirdPartyAppAnalytics) {
              subBuilder.MergeFrom(ThirdPartyAppAnalytics);
            }
            input.ReadMessage(subBuilder);
            ThirdPartyAppAnalytics = subBuilder;
            break;
          }
          case 50: {
            global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.DataPartnerLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.DataPartner) {
              subBuilder.MergeFrom(DataPartner);
            }
            input.ReadMessage(subBuilder);
            DataPartner = subBuilder;
            break;
          }
          case 58: {
            global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.GoogleAdsLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.GoogleAds) {
              subBuilder.MergeFrom(GoogleAds);
            }
            input.ReadMessage(subBuilder);
            GoogleAds = subBuilder;
            break;
          }
          case 64: {
            AccountLinkId = input.ReadInt64();
            break;
          }
          case 74: {
            global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier subBuilder = new global::Google.Ads.GoogleAds.V11.Resources.HotelCenterLinkIdentifier();
            if (linkedAccountCase_ == LinkedAccountOneofCase.HotelCenter) {
              subBuilder.MergeFrom(HotelCenter);
            }
            input.ReadMessage(subBuilder);
            HotelCenter = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The identifiers of a Third Party App Analytics Link.
  /// </summary>
  public sealed partial class ThirdPartyAppAnalyticsLinkIdentifier : pb::IMessage<ThirdPartyAppAnalyticsLinkIdentifier>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ThirdPartyAppAnalyticsLinkIdentifier> _parser = new pb::MessageParser<ThirdPartyAppAnalyticsLinkIdentifier>(() => new ThirdPartyAppAnalyticsLinkIdentifier());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ThirdPartyAppAnalyticsLinkIdentifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V11.Resources.AccountLinkReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThirdPartyAppAnalyticsLinkIdentifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThirdPartyAppAnalyticsLinkIdentifier(ThirdPartyAppAnalyticsLinkIdentifier other) : this() {
      _hasBits0 = other._hasBits0;
      appAnalyticsProviderId_ = other.appAnalyticsProviderId_;
      appId_ = other.appId_;
      appVendor_ = other.appVendor_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ThirdPartyAppAnalyticsLinkIdentifier Clone() {
      return new ThirdPartyAppAnalyticsLinkIdentifier(this);
    }

    /// <summary>Field number for the "app_analytics_provider_id" field.</summary>
    public const int AppAnalyticsProviderIdFieldNumber = 4;
    private long appAnalyticsProviderId_;
    /// <summary>
    /// Immutable. The ID of the app analytics provider.
    /// This field should not be empty when creating a new third
    /// party app analytics link. It is unable to be modified after the creation of
    /// the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AppAnalyticsProviderId {
      get { if ((_hasBits0 & 1) != 0) { return appAnalyticsProviderId_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        appAnalyticsProviderId_ = value;
      }
    }
    /// <summary>Gets whether the "app_analytics_provider_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppAnalyticsProviderId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "app_analytics_provider_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppAnalyticsProviderId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 5;
    private string appId_;
    /// <summary>
    /// Immutable. A string that uniquely identifies a mobile application from which the data
    /// was collected to the Google Ads API. For iOS, the ID string is the 9 digit
    /// string that appears at the end of an App Store URL (for example,
    /// "422689480" for "Gmail" whose App Store link is
    /// https://apps.apple.com/us/app/gmail-email-by-google/id422689480). For
    /// Android, the ID string is the application's package name (for example,
    /// "com.google.android.gm" for "Gmail" given Google Play link
    /// https://play.google.com/store/apps/details?id=com.google.android.gm)
    /// This field should not be empty when creating a new third
    /// party app analytics link. It is unable to be modified after the creation of
    /// the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppId {
      get { return appId_ ?? ""; }
      set {
        appId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "app_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppId {
      get { return appId_ != null; }
    }
    /// <summary>Clears the value of the "app_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppId() {
      appId_ = null;
    }

    /// <summary>Field number for the "app_vendor" field.</summary>
    public const int AppVendorFieldNumber = 3;
    private global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor appVendor_ = global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified;
    /// <summary>
    /// Immutable. The vendor of the app.
    /// This field should not be empty when creating a new third
    /// party app analytics link. It is unable to be modified after the creation of
    /// the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor AppVendor {
      get { return appVendor_; }
      set {
        appVendor_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ThirdPartyAppAnalyticsLinkIdentifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ThirdPartyAppAnalyticsLinkIdentifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppAnalyticsProviderId != other.AppAnalyticsProviderId) return false;
      if (AppId != other.AppId) return false;
      if (AppVendor != other.AppVendor) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasAppAnalyticsProviderId) hash ^= AppAnalyticsProviderId.GetHashCode();
      if (HasAppId) hash ^= AppId.GetHashCode();
      if (AppVendor != global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified) hash ^= AppVendor.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AppVendor != global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AppVendor);
      }
      if (HasAppAnalyticsProviderId) {
        output.WriteRawTag(32);
        output.WriteInt64(AppAnalyticsProviderId);
      }
      if (HasAppId) {
        output.WriteRawTag(42);
        output.WriteString(AppId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AppVendor != global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) AppVendor);
      }
      if (HasAppAnalyticsProviderId) {
        output.WriteRawTag(32);
        output.WriteInt64(AppAnalyticsProviderId);
      }
      if (HasAppId) {
        output.WriteRawTag(42);
        output.WriteString(AppId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasAppAnalyticsProviderId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AppAnalyticsProviderId);
      }
      if (HasAppId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppId);
      }
      if (AppVendor != global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AppVendor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ThirdPartyAppAnalyticsLinkIdentifier other) {
      if (other == null) {
        return;
      }
      if (other.HasAppAnalyticsProviderId) {
        AppAnalyticsProviderId = other.AppAnalyticsProviderId;
      }
      if (other.HasAppId) {
        AppId = other.AppId;
      }
      if (other.AppVendor != global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor.Unspecified) {
        AppVendor = other.AppVendor;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 24: {
            AppVendor = (global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor) input.ReadEnum();
            break;
          }
          case 32: {
            AppAnalyticsProviderId = input.ReadInt64();
            break;
          }
          case 42: {
            AppId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 24: {
            AppVendor = (global::Google.Ads.GoogleAds.V11.Enums.MobileAppVendorEnum.Types.MobileAppVendor) input.ReadEnum();
            break;
          }
          case 32: {
            AppAnalyticsProviderId = input.ReadInt64();
            break;
          }
          case 42: {
            AppId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The identifier for Data Partner account.
  /// </summary>
  public sealed partial class DataPartnerLinkIdentifier : pb::IMessage<DataPartnerLinkIdentifier>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DataPartnerLinkIdentifier> _parser = new pb::MessageParser<DataPartnerLinkIdentifier>(() => new DataPartnerLinkIdentifier());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DataPartnerLinkIdentifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V11.Resources.AccountLinkReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataPartnerLinkIdentifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataPartnerLinkIdentifier(DataPartnerLinkIdentifier other) : this() {
      _hasBits0 = other._hasBits0;
      dataPartnerId_ = other.dataPartnerId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataPartnerLinkIdentifier Clone() {
      return new DataPartnerLinkIdentifier(this);
    }

    /// <summary>Field number for the "data_partner_id" field.</summary>
    public const int DataPartnerIdFieldNumber = 1;
    private long dataPartnerId_;
    /// <summary>
    /// Immutable. The customer ID of the Data partner account.
    /// This field is required and should not be empty when creating a new
    /// data partner link. It is unable to be modified after the creation of
    /// the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DataPartnerId {
      get { if ((_hasBits0 & 1) != 0) { return dataPartnerId_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        dataPartnerId_ = value;
      }
    }
    /// <summary>Gets whether the "data_partner_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDataPartnerId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "data_partner_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDataPartnerId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DataPartnerLinkIdentifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DataPartnerLinkIdentifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DataPartnerId != other.DataPartnerId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasDataPartnerId) hash ^= DataPartnerId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasDataPartnerId) {
        output.WriteRawTag(8);
        output.WriteInt64(DataPartnerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasDataPartnerId) {
        output.WriteRawTag(8);
        output.WriteInt64(DataPartnerId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasDataPartnerId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DataPartnerId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DataPartnerLinkIdentifier other) {
      if (other == null) {
        return;
      }
      if (other.HasDataPartnerId) {
        DataPartnerId = other.DataPartnerId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DataPartnerId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DataPartnerId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The identifier for Hotel account.
  /// </summary>
  public sealed partial class HotelCenterLinkIdentifier : pb::IMessage<HotelCenterLinkIdentifier>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HotelCenterLinkIdentifier> _parser = new pb::MessageParser<HotelCenterLinkIdentifier>(() => new HotelCenterLinkIdentifier());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HotelCenterLinkIdentifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V11.Resources.AccountLinkReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HotelCenterLinkIdentifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HotelCenterLinkIdentifier(HotelCenterLinkIdentifier other) : this() {
      hotelCenterId_ = other.hotelCenterId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HotelCenterLinkIdentifier Clone() {
      return new HotelCenterLinkIdentifier(this);
    }

    /// <summary>Field number for the "hotel_center_id" field.</summary>
    public const int HotelCenterIdFieldNumber = 1;
    private long hotelCenterId_;
    /// <summary>
    /// Output only. The hotel center id of the hotel account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HotelCenterId {
      get { return hotelCenterId_; }
      set {
        hotelCenterId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HotelCenterLinkIdentifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HotelCenterLinkIdentifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HotelCenterId != other.HotelCenterId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HotelCenterId != 0L) hash ^= HotelCenterId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HotelCenterId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(HotelCenterId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HotelCenterId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(HotelCenterId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HotelCenterId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HotelCenterId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HotelCenterLinkIdentifier other) {
      if (other == null) {
        return;
      }
      if (other.HotelCenterId != 0L) {
        HotelCenterId = other.HotelCenterId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HotelCenterId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            HotelCenterId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The identifier for Google Ads account.
  /// </summary>
  public sealed partial class GoogleAdsLinkIdentifier : pb::IMessage<GoogleAdsLinkIdentifier>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GoogleAdsLinkIdentifier> _parser = new pb::MessageParser<GoogleAdsLinkIdentifier>(() => new GoogleAdsLinkIdentifier());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GoogleAdsLinkIdentifier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V11.Resources.AccountLinkReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAdsLinkIdentifier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAdsLinkIdentifier(GoogleAdsLinkIdentifier other) : this() {
      customer_ = other.customer_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GoogleAdsLinkIdentifier Clone() {
      return new GoogleAdsLinkIdentifier(this);
    }

    /// <summary>Field number for the "customer" field.</summary>
    public const int CustomerFieldNumber = 3;
    private string customer_;
    /// <summary>
    /// Immutable. The resource name of the Google Ads account.
    /// This field is required and should not be empty when creating a new
    /// Google Ads link. It is unable to be modified after the creation of
    /// the link.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Customer {
      get { return customer_ ?? ""; }
      set {
        customer_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "customer" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCustomer {
      get { return customer_ != null; }
    }
    /// <summary>Clears the value of the "customer" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCustomer() {
      customer_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GoogleAdsLinkIdentifier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GoogleAdsLinkIdentifier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Customer != other.Customer) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCustomer) hash ^= Customer.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCustomer) {
        output.WriteRawTag(26);
        output.WriteString(Customer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCustomer) {
        output.WriteRawTag(26);
        output.WriteString(Customer);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCustomer) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Customer);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GoogleAdsLinkIdentifier other) {
      if (other == null) {
        return;
      }
      if (other.HasCustomer) {
        Customer = other.Customer;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 26: {
            Customer = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 26: {
            Customer = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
