// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ads/googleads/v24/enums/optimize_assets_experiment_subtype.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ads.GoogleAds.V24.Enums {

  /// <summary>Holder for reflection information generated from google/ads/googleads/v24/enums/optimize_assets_experiment_subtype.proto</summary>
  public static partial class OptimizeAssetsExperimentSubtypeReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ads/googleads/v24/enums/optimize_assets_experiment_subtype.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptimizeAssetsExperimentSubtypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ckdnb29nbGUvYWRzL2dvb2dsZWFkcy92MjQvZW51bXMvb3B0aW1pemVfYXNz",
            "ZXRzX2V4cGVyaW1lbnRfc3VidHlwZS5wcm90bxIeZ29vZ2xlLmFkcy5nb29n",
            "bGVhZHMudjI0LmVudW1zIsIBCiNPcHRpbWl6ZUFzc2V0c0V4cGVyaW1lbnRT",
            "dWJ0eXBlRW51bSKaAQofT3B0aW1pemVBc3NldHNFeHBlcmltZW50U3VidHlw",
            "ZRIPCgtVTlNQRUNJRklFRBAAEgsKB1VOS05PV04QARIiCh5BRERfQVNTRVRT",
            "X1RPX0FTU0VUTEVTU19SRVRBSUwQAhIhCh1BRERfVklERU9fQVNTRVRTX1RP",
            "X1ZJREVPTEVTUxADEhIKDkNPTVBBUkVfQVNTRVRTEARC/gEKImNvbS5nb29n",
            "bGUuYWRzLmdvb2dsZWFkcy52MjQuZW51bXNCJE9wdGltaXplQXNzZXRzRXhw",
            "ZXJpbWVudFN1YnR5cGVQcm90b1ABWkNnb29nbGUuZ29sYW5nLm9yZy9nZW5w",
            "cm90by9nb29nbGVhcGlzL2Fkcy9nb29nbGVhZHMvdjI0L2VudW1zO2VudW1z",
            "ogIDR0FBqgIeR29vZ2xlLkFkcy5Hb29nbGVBZHMuVjI0LkVudW1zygIeR29v",
            "Z2xlXEFkc1xHb29nbGVBZHNcVjI0XEVudW1z6gIiR29vZ2xlOjpBZHM6Okdv",
            "b2dsZUFkczo6VjI0OjpFbnVtc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V24.Enums.OptimizeAssetsExperimentSubtypeEnum), global::Google.Ads.GoogleAds.V24.Enums.OptimizeAssetsExperimentSubtypeEnum.Parser, null, null, new[]{ typeof(global::Google.Ads.GoogleAds.V24.Enums.OptimizeAssetsExperimentSubtypeEnum.Types.OptimizeAssetsExperimentSubtype) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Indicates the subtype of an optimize assets experiment.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OptimizeAssetsExperimentSubtypeEnum : pb::IMessage<OptimizeAssetsExperimentSubtypeEnum>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OptimizeAssetsExperimentSubtypeEnum> _parser = new pb::MessageParser<OptimizeAssetsExperimentSubtypeEnum>(() => new OptimizeAssetsExperimentSubtypeEnum());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OptimizeAssetsExperimentSubtypeEnum> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V24.Enums.OptimizeAssetsExperimentSubtypeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptimizeAssetsExperimentSubtypeEnum() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptimizeAssetsExperimentSubtypeEnum(OptimizeAssetsExperimentSubtypeEnum other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OptimizeAssetsExperimentSubtypeEnum Clone() {
      return new OptimizeAssetsExperimentSubtypeEnum(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OptimizeAssetsExperimentSubtypeEnum);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OptimizeAssetsExperimentSubtypeEnum other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OptimizeAssetsExperimentSubtypeEnum other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OptimizeAssetsExperimentSubtypeEnum message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// The enum describing optimize assets subtype.
      /// </summary>
      public enum OptimizeAssetsExperimentSubtype {
        /// <summary>
        /// Not specified.
        /// </summary>
        [pbr::OriginalName("UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// The value is unknown in this version.
        /// </summary>
        [pbr::OriginalName("UNKNOWN")] Unknown = 1,
        /// <summary>
        /// The experiment is testing adding assets to
        /// assetless retail PMax experiment.
        /// </summary>
        [pbr::OriginalName("ADD_ASSETS_TO_ASSETLESS_RETAIL")] AddAssetsToAssetlessRetail = 2,
        /// <summary>
        /// The experiment is testing adding video assets to
        /// videoless PMax experiment.
        /// </summary>
        [pbr::OriginalName("ADD_VIDEO_ASSETS_TO_VIDEOLESS")] AddVideoAssetsToVideoless = 3,
        /// <summary>
        /// The experiment is testing comparing two different sets
        /// of assets in a PMax experiment.
        /// </summary>
        [pbr::OriginalName("COMPARE_ASSETS")] CompareAssets = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
