// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ads/googleads/v21/resources/offline_conversion_upload_client_summary.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ads.GoogleAds.V21.Resources {

  /// <summary>Holder for reflection information generated from google/ads/googleads/v21/resources/offline_conversion_upload_client_summary.proto</summary>
  public static partial class OfflineConversionUploadClientSummaryReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ads/googleads/v21/resources/offline_conversion_upload_client_summary.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OfflineConversionUploadClientSummaryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ClFnb29nbGUvYWRzL2dvb2dsZWFkcy92MjEvcmVzb3VyY2VzL29mZmxpbmVf",
            "Y29udmVyc2lvbl91cGxvYWRfY2xpZW50X3N1bW1hcnkucHJvdG8SImdvb2ds",
            "ZS5hZHMuZ29vZ2xlYWRzLnYyMS5yZXNvdXJjZXMaTmdvb2dsZS9hZHMvZ29v",
            "Z2xlYWRzL3YyMS9lbnVtcy9vZmZsaW5lX2NvbnZlcnNpb25fZGlhZ25vc3Rp",
            "Y19zdGF0dXNfZW51bS5wcm90bxpFZ29vZ2xlL2Fkcy9nb29nbGVhZHMvdjIx",
            "L2VudW1zL29mZmxpbmVfZXZlbnRfdXBsb2FkX2NsaWVudF9lbnVtLnByb3Rv",
            "Gjtnb29nbGUvYWRzL2dvb2dsZWFkcy92MjEvZXJyb3JzL2NvbGxlY3Rpb25f",
            "c2l6ZV9lcnJvci5wcm90bxpIZ29vZ2xlL2Fkcy9nb29nbGVhZHMvdjIxL2Vy",
            "cm9ycy9jb252ZXJzaW9uX2FkanVzdG1lbnRfdXBsb2FkX2Vycm9yLnByb3Rv",
            "Gj1nb29nbGUvYWRzL2dvb2dsZWFkcy92MjEvZXJyb3JzL2NvbnZlcnNpb25f",
            "dXBsb2FkX2Vycm9yLnByb3RvGjBnb29nbGUvYWRzL2dvb2dsZWFkcy92MjEv",
            "ZXJyb3JzL2RhdGVfZXJyb3IucHJvdG8aNGdvb2dsZS9hZHMvZ29vZ2xlYWRz",
            "L3YyMS9lcnJvcnMvZGlzdGluY3RfZXJyb3IucHJvdG8aMWdvb2dsZS9hZHMv",
            "Z29vZ2xlYWRzL3YyMS9lcnJvcnMvZmllbGRfZXJyb3IucHJvdG8aMmdvb2ds",
            "ZS9hZHMvZ29vZ2xlYWRzL3YyMS9lcnJvcnMvbXV0YXRlX2Vycm9yLnByb3Rv",
            "Gjtnb29nbGUvYWRzL2dvb2dsZWFkcy92MjEvZXJyb3JzL25vdF9hbGxvd2xp",
            "c3RlZF9lcnJvci5wcm90bxo5Z29vZ2xlL2Fkcy9nb29nbGVhZHMvdjIxL2Vy",
            "cm9ycy9zdHJpbmdfZm9ybWF0X2Vycm9yLnByb3RvGjlnb29nbGUvYWRzL2dv",
            "b2dsZWFkcy92MjEvZXJyb3JzL3N0cmluZ19sZW5ndGhfZXJyb3IucHJvdG8a",
            "H2dvb2dsZS9hcGkvZmllbGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkv",
            "cmVzb3VyY2UucHJvdG8ixQcKJE9mZmxpbmVDb252ZXJzaW9uVXBsb2FkQ2xp",
            "ZW50U3VtbWFyeRJcCg1yZXNvdXJjZV9uYW1lGAEgASgJQkXgQQP6QT8KPWdv",
            "b2dsZWFkcy5nb29nbGVhcGlzLmNvbS9PZmZsaW5lQ29udmVyc2lvblVwbG9h",
            "ZENsaWVudFN1bW1hcnkSagoGY2xpZW50GAIgASgOMlUuZ29vZ2xlLmFkcy5n",
            "b29nbGVhZHMudjIxLmVudW1zLk9mZmxpbmVFdmVudFVwbG9hZENsaWVudEVu",
            "dW0uT2ZmbGluZUV2ZW50VXBsb2FkQ2xpZW50QgPgQQMSfAoGc3RhdHVzGAMg",
            "ASgOMmcuZ29vZ2xlLmFkcy5nb29nbGVhZHMudjIxLmVudW1zLk9mZmxpbmVD",
            "b252ZXJzaW9uRGlhZ25vc3RpY1N0YXR1c0VudW0uT2ZmbGluZUNvbnZlcnNp",
            "b25EaWFnbm9zdGljU3RhdHVzQgPgQQMSHgoRdG90YWxfZXZlbnRfY291bnQY",
            "BCABKANCA+BBAxIjChZzdWNjZXNzZnVsX2V2ZW50X2NvdW50GAUgASgDQgPg",
            "QQMSGQoMc3VjY2Vzc19yYXRlGAYgASgBQgPgQQMSIAoTcGVuZGluZ19ldmVu",
            "dF9jb3VudBgLIAEoA0ID4EEDEhkKDHBlbmRpbmdfcmF0ZRgMIAEoAUID4EED",
            "EiIKFWxhc3RfdXBsb2FkX2RhdGVfdGltZRgHIAEoCUID4EEDEloKD2RhaWx5",
            "X3N1bW1hcmllcxgIIAMoCzI8Lmdvb2dsZS5hZHMuZ29vZ2xlYWRzLnYyMS5y",
            "ZXNvdXJjZXMuT2ZmbGluZUNvbnZlcnNpb25TdW1tYXJ5QgPgQQMSWAoNam9i",
            "X3N1bW1hcmllcxgJIAMoCzI8Lmdvb2dsZS5hZHMuZ29vZ2xlYWRzLnYyMS5y",
            "ZXNvdXJjZXMuT2ZmbGluZUNvbnZlcnNpb25TdW1tYXJ5QgPgQQMSTwoGYWxl",
            "cnRzGAogAygLMjouZ29vZ2xlLmFkcy5nb29nbGVhZHMudjIxLnJlc291cmNl",
            "cy5PZmZsaW5lQ29udmVyc2lvbkFsZXJ0QgPgQQM6jAHqQYgBCj1nb29nbGVh",
            "ZHMuZ29vZ2xlYXBpcy5jb20vT2ZmbGluZUNvbnZlcnNpb25VcGxvYWRDbGll",
            "bnRTdW1tYXJ5EkdjdXN0b21lcnMve2N1c3RvbWVyX2lkfS9vZmZsaW5lQ29u",
            "dmVyc2lvblVwbG9hZENsaWVudFN1bW1hcmllcy97Y2xpZW50fSK0AQoYT2Zm",
            "bGluZUNvbnZlcnNpb25TdW1tYXJ5Eh0KEHN1Y2Nlc3NmdWxfY291bnQYAyAB",
            "KANCA+BBAxIZCgxmYWlsZWRfY291bnQYBCABKANCA+BBAxIaCg1wZW5kaW5n",
            "X2NvdW50GAUgASgDQgPgQQMSFQoGam9iX2lkGAEgASgDQgPgQQNIABIaCgt1",
            "cGxvYWRfZGF0ZRgCIAEoCUID4EEDSABCDwoNZGltZW5zaW9uX2tleSKHAQoW",
            "T2ZmbGluZUNvbnZlcnNpb25BbGVydBJOCgVlcnJvchgBIAEoCzI6Lmdvb2ds",
            "ZS5hZHMuZ29vZ2xlYWRzLnYyMS5yZXNvdXJjZXMuT2ZmbGluZUNvbnZlcnNp",
            "b25FcnJvckID4EEDEh0KEGVycm9yX3BlcmNlbnRhZ2UYAiABKAFCA+BBAyLn",
            "CAoWT2ZmbGluZUNvbnZlcnNpb25FcnJvchJyChVjb2xsZWN0aW9uX3NpemVf",
            "ZXJyb3IYASABKA4yTC5nb29nbGUuYWRzLmdvb2dsZWFkcy52MjEuZXJyb3Jz",
            "LkNvbGxlY3Rpb25TaXplRXJyb3JFbnVtLkNvbGxlY3Rpb25TaXplRXJyb3JC",
            "A+BBA0gAEpcBCiJjb252ZXJzaW9uX2FkanVzdG1lbnRfdXBsb2FkX2Vycm9y",
            "GAIgASgOMmQuZ29vZ2xlLmFkcy5nb29nbGVhZHMudjIxLmVycm9ycy5Db252",
            "ZXJzaW9uQWRqdXN0bWVudFVwbG9hZEVycm9yRW51bS5Db252ZXJzaW9uQWRq",
            "dXN0bWVudFVwbG9hZEVycm9yQgPgQQNIABJ4Chdjb252ZXJzaW9uX3VwbG9h",
            "ZF9lcnJvchgDIAEoDjJQLmdvb2dsZS5hZHMuZ29vZ2xlYWRzLnYyMS5lcnJv",
            "cnMuQ29udmVyc2lvblVwbG9hZEVycm9yRW51bS5Db252ZXJzaW9uVXBsb2Fk",
            "RXJyb3JCA+BBA0gAElMKCmRhdGVfZXJyb3IYBCABKA4yOC5nb29nbGUuYWRz",
            "Lmdvb2dsZWFkcy52MjEuZXJyb3JzLkRhdGVFcnJvckVudW0uRGF0ZUVycm9y",
            "QgPgQQNIABJfCg5kaXN0aW5jdF9lcnJvchgFIAEoDjJALmdvb2dsZS5hZHMu",
            "Z29vZ2xlYWRzLnYyMS5lcnJvcnMuRGlzdGluY3RFcnJvckVudW0uRGlzdGlu",
            "Y3RFcnJvckID4EEDSAASVgoLZmllbGRfZXJyb3IYBiABKA4yOi5nb29nbGUu",
            "YWRzLmdvb2dsZWFkcy52MjEuZXJyb3JzLkZpZWxkRXJyb3JFbnVtLkZpZWxk",
            "RXJyb3JCA+BBA0gAElkKDG11dGF0ZV9lcnJvchgHIAEoDjI8Lmdvb2dsZS5h",
            "ZHMuZ29vZ2xlYWRzLnYyMS5lcnJvcnMuTXV0YXRlRXJyb3JFbnVtLk11dGF0",
            "ZUVycm9yQgPgQQNIABJyChVub3RfYWxsb3dsaXN0ZWRfZXJyb3IYCCABKA4y",
            "TC5nb29nbGUuYWRzLmdvb2dsZWFkcy52MjEuZXJyb3JzLk5vdEFsbG93bGlz",
            "dGVkRXJyb3JFbnVtLk5vdEFsbG93bGlzdGVkRXJyb3JCA+BBA0gAEmwKE3N0",
            "cmluZ19mb3JtYXRfZXJyb3IYCSABKA4ySC5nb29nbGUuYWRzLmdvb2dsZWFk",
            "cy52MjEuZXJyb3JzLlN0cmluZ0Zvcm1hdEVycm9yRW51bS5TdHJpbmdGb3Jt",
            "YXRFcnJvckID4EEDSAASbAoTc3RyaW5nX2xlbmd0aF9lcnJvchgKIAEoDjJI",
            "Lmdvb2dsZS5hZHMuZ29vZ2xlYWRzLnYyMS5lcnJvcnMuU3RyaW5nTGVuZ3Ro",
            "RXJyb3JFbnVtLlN0cmluZ0xlbmd0aEVycm9yQgPgQQNIAEIMCgplcnJvcl9j",
            "b2RlQpsCCiZjb20uZ29vZ2xlLmFkcy5nb29nbGVhZHMudjIxLnJlc291cmNl",
            "c0IpT2ZmbGluZUNvbnZlcnNpb25VcGxvYWRDbGllbnRTdW1tYXJ5UHJvdG9Q",
            "AVpLZ29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJvdG8vZ29vZ2xlYXBpcy9hZHMv",
            "Z29vZ2xlYWRzL3YyMS9yZXNvdXJjZXM7cmVzb3VyY2VzogIDR0FBqgIiR29v",
            "Z2xlLkFkcy5Hb29nbGVBZHMuVjIxLlJlc291cmNlc8oCIkdvb2dsZVxBZHNc",
            "R29vZ2xlQWRzXFYyMVxSZXNvdXJjZXPqAiZHb29nbGU6OkFkczo6R29vZ2xl",
            "QWRzOjpWMjE6OlJlc291cmNlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnumReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnumReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.CollectionSizeErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.ConversionAdjustmentUploadErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.ConversionUploadErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.DateErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.DistinctErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.FieldErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.MutateErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.NotAllowlistedErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.StringFormatErrorReflection.Descriptor, global::Google.Ads.GoogleAds.V21.Errors.StringLengthErrorReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummary), global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummary.Parser, new[]{ "ResourceName", "Client", "Status", "TotalEventCount", "SuccessfulEventCount", "SuccessRate", "PendingEventCount", "PendingRate", "LastUploadDateTime", "DailySummaries", "JobSummaries", "Alerts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary), global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary.Parser, new[]{ "SuccessfulCount", "FailedCount", "PendingCount", "JobId", "UploadDate" }, new[]{ "DimensionKey" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert), global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert.Parser, new[]{ "Error", "ErrorPercentage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError), global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError.Parser, new[]{ "CollectionSizeError", "ConversionAdjustmentUploadError", "ConversionUploadError", "DateError", "DistinctError", "FieldError", "MutateError", "NotAllowlistedError", "StringFormatError", "StringLengthError" }, new[]{ "ErrorCode" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Offline conversion upload summary at customer level.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OfflineConversionUploadClientSummary : pb::IMessage<OfflineConversionUploadClientSummary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OfflineConversionUploadClientSummary> _parser = new pb::MessageParser<OfflineConversionUploadClientSummary>(() => new OfflineConversionUploadClientSummary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OfflineConversionUploadClientSummary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummaryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionUploadClientSummary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionUploadClientSummary(OfflineConversionUploadClientSummary other) : this() {
      resourceName_ = other.resourceName_;
      client_ = other.client_;
      status_ = other.status_;
      totalEventCount_ = other.totalEventCount_;
      successfulEventCount_ = other.successfulEventCount_;
      successRate_ = other.successRate_;
      pendingEventCount_ = other.pendingEventCount_;
      pendingRate_ = other.pendingRate_;
      lastUploadDateTime_ = other.lastUploadDateTime_;
      dailySummaries_ = other.dailySummaries_.Clone();
      jobSummaries_ = other.jobSummaries_.Clone();
      alerts_ = other.alerts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionUploadClientSummary Clone() {
      return new OfflineConversionUploadClientSummary(this);
    }

    /// <summary>Field number for the "resource_name" field.</summary>
    public const int ResourceNameFieldNumber = 1;
    private string resourceName_ = "";
    /// <summary>
    /// Output only. The resource name of the offline conversion upload summary at
    /// customer level. Offline conversion upload client summary resource names
    /// have the form:
    ///
    /// `customers/{customer_id}/offlineConversionUploadClientSummaries/{client}`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceName {
      get { return resourceName_; }
      set {
        resourceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client" field.</summary>
    public const int ClientFieldNumber = 2;
    private global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient client_ = global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified;
    /// <summary>
    /// Output only. Client type of the upload event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient Client {
      get { return client_; }
      set {
        client_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus status_ = global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified;
    /// <summary>
    /// Output only. Overall status for offline conversion client summary. Status
    /// is generated from most recent calendar day with upload stats.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "total_event_count" field.</summary>
    public const int TotalEventCountFieldNumber = 4;
    private long totalEventCount_;
    /// <summary>
    /// Output only. Total count of uploaded events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalEventCount {
      get { return totalEventCount_; }
      set {
        totalEventCount_ = value;
      }
    }

    /// <summary>Field number for the "successful_event_count" field.</summary>
    public const int SuccessfulEventCountFieldNumber = 5;
    private long successfulEventCount_;
    /// <summary>
    /// Output only. Total count of successful uploaded events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SuccessfulEventCount {
      get { return successfulEventCount_; }
      set {
        successfulEventCount_ = value;
      }
    }

    /// <summary>Field number for the "success_rate" field.</summary>
    public const int SuccessRateFieldNumber = 6;
    private double successRate_;
    /// <summary>
    /// Output only. Successful rate.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SuccessRate {
      get { return successRate_; }
      set {
        successRate_ = value;
      }
    }

    /// <summary>Field number for the "pending_event_count" field.</summary>
    public const int PendingEventCountFieldNumber = 11;
    private long pendingEventCount_;
    /// <summary>
    /// Output only. Total count of pending uploaded events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PendingEventCount {
      get { return pendingEventCount_; }
      set {
        pendingEventCount_ = value;
      }
    }

    /// <summary>Field number for the "pending_rate" field.</summary>
    public const int PendingRateFieldNumber = 12;
    private double pendingRate_;
    /// <summary>
    /// Output only. The ratio of total pending events to total events.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double PendingRate {
      get { return pendingRate_; }
      set {
        pendingRate_ = value;
      }
    }

    /// <summary>Field number for the "last_upload_date_time" field.</summary>
    public const int LastUploadDateTimeFieldNumber = 7;
    private string lastUploadDateTime_ = "";
    /// <summary>
    /// Output only. Date for the latest upload batch. The format is "yyyy-mm-dd
    /// hh:mm:ss", and it's in the time zone of the Google Ads account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastUploadDateTime {
      get { return lastUploadDateTime_; }
      set {
        lastUploadDateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "daily_summaries" field.</summary>
    public const int DailySummariesFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> _repeated_dailySummaries_codec
        = pb::FieldCodec.ForMessage(66, global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary.Parser);
    private readonly pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> dailySummaries_ = new pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary>();
    /// <summary>
    /// Output only. Summary of history stats by last N days.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> DailySummaries {
      get { return dailySummaries_; }
    }

    /// <summary>Field number for the "job_summaries" field.</summary>
    public const int JobSummariesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> _repeated_jobSummaries_codec
        = pb::FieldCodec.ForMessage(74, global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary.Parser);
    private readonly pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> jobSummaries_ = new pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary>();
    /// <summary>
    /// Output only. Summary of history stats by last N jobs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionSummary> JobSummaries {
      get { return jobSummaries_; }
    }

    /// <summary>Field number for the "alerts" field.</summary>
    public const int AlertsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert> _repeated_alerts_codec
        = pb::FieldCodec.ForMessage(82, global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert.Parser);
    private readonly pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert> alerts_ = new pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert>();
    /// <summary>
    /// Output only. Details for each error code. Alerts are generated from most
    /// recent calendar day with upload stats.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionAlert> Alerts {
      get { return alerts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OfflineConversionUploadClientSummary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OfflineConversionUploadClientSummary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceName != other.ResourceName) return false;
      if (Client != other.Client) return false;
      if (Status != other.Status) return false;
      if (TotalEventCount != other.TotalEventCount) return false;
      if (SuccessfulEventCount != other.SuccessfulEventCount) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SuccessRate, other.SuccessRate)) return false;
      if (PendingEventCount != other.PendingEventCount) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PendingRate, other.PendingRate)) return false;
      if (LastUploadDateTime != other.LastUploadDateTime) return false;
      if(!dailySummaries_.Equals(other.dailySummaries_)) return false;
      if(!jobSummaries_.Equals(other.jobSummaries_)) return false;
      if(!alerts_.Equals(other.alerts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceName.Length != 0) hash ^= ResourceName.GetHashCode();
      if (Client != global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified) hash ^= Client.GetHashCode();
      if (Status != global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified) hash ^= Status.GetHashCode();
      if (TotalEventCount != 0L) hash ^= TotalEventCount.GetHashCode();
      if (SuccessfulEventCount != 0L) hash ^= SuccessfulEventCount.GetHashCode();
      if (SuccessRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SuccessRate);
      if (PendingEventCount != 0L) hash ^= PendingEventCount.GetHashCode();
      if (PendingRate != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PendingRate);
      if (LastUploadDateTime.Length != 0) hash ^= LastUploadDateTime.GetHashCode();
      hash ^= dailySummaries_.GetHashCode();
      hash ^= jobSummaries_.GetHashCode();
      hash ^= alerts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      if (Client != global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Client);
      }
      if (Status != global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (TotalEventCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TotalEventCount);
      }
      if (SuccessfulEventCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SuccessfulEventCount);
      }
      if (SuccessRate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(SuccessRate);
      }
      if (LastUploadDateTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LastUploadDateTime);
      }
      dailySummaries_.WriteTo(output, _repeated_dailySummaries_codec);
      jobSummaries_.WriteTo(output, _repeated_jobSummaries_codec);
      alerts_.WriteTo(output, _repeated_alerts_codec);
      if (PendingEventCount != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(PendingEventCount);
      }
      if (PendingRate != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(PendingRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      if (Client != global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Client);
      }
      if (Status != global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (TotalEventCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TotalEventCount);
      }
      if (SuccessfulEventCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SuccessfulEventCount);
      }
      if (SuccessRate != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(SuccessRate);
      }
      if (LastUploadDateTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LastUploadDateTime);
      }
      dailySummaries_.WriteTo(ref output, _repeated_dailySummaries_codec);
      jobSummaries_.WriteTo(ref output, _repeated_jobSummaries_codec);
      alerts_.WriteTo(ref output, _repeated_alerts_codec);
      if (PendingEventCount != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(PendingEventCount);
      }
      if (PendingRate != 0D) {
        output.WriteRawTag(97);
        output.WriteDouble(PendingRate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResourceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceName);
      }
      if (Client != global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Client);
      }
      if (Status != global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (TotalEventCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalEventCount);
      }
      if (SuccessfulEventCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SuccessfulEventCount);
      }
      if (SuccessRate != 0D) {
        size += 1 + 8;
      }
      if (PendingEventCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PendingEventCount);
      }
      if (PendingRate != 0D) {
        size += 1 + 8;
      }
      if (LastUploadDateTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastUploadDateTime);
      }
      size += dailySummaries_.CalculateSize(_repeated_dailySummaries_codec);
      size += jobSummaries_.CalculateSize(_repeated_jobSummaries_codec);
      size += alerts_.CalculateSize(_repeated_alerts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OfflineConversionUploadClientSummary other) {
      if (other == null) {
        return;
      }
      if (other.ResourceName.Length != 0) {
        ResourceName = other.ResourceName;
      }
      if (other.Client != global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient.Unspecified) {
        Client = other.Client;
      }
      if (other.Status != global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.TotalEventCount != 0L) {
        TotalEventCount = other.TotalEventCount;
      }
      if (other.SuccessfulEventCount != 0L) {
        SuccessfulEventCount = other.SuccessfulEventCount;
      }
      if (other.SuccessRate != 0D) {
        SuccessRate = other.SuccessRate;
      }
      if (other.PendingEventCount != 0L) {
        PendingEventCount = other.PendingEventCount;
      }
      if (other.PendingRate != 0D) {
        PendingRate = other.PendingRate;
      }
      if (other.LastUploadDateTime.Length != 0) {
        LastUploadDateTime = other.LastUploadDateTime;
      }
      dailySummaries_.Add(other.dailySummaries_);
      jobSummaries_.Add(other.jobSummaries_);
      alerts_.Add(other.alerts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 16: {
            Client = (global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient) input.ReadEnum();
            break;
          }
          case 24: {
            Status = (global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus) input.ReadEnum();
            break;
          }
          case 32: {
            TotalEventCount = input.ReadInt64();
            break;
          }
          case 40: {
            SuccessfulEventCount = input.ReadInt64();
            break;
          }
          case 49: {
            SuccessRate = input.ReadDouble();
            break;
          }
          case 58: {
            LastUploadDateTime = input.ReadString();
            break;
          }
          case 66: {
            dailySummaries_.AddEntriesFrom(input, _repeated_dailySummaries_codec);
            break;
          }
          case 74: {
            jobSummaries_.AddEntriesFrom(input, _repeated_jobSummaries_codec);
            break;
          }
          case 82: {
            alerts_.AddEntriesFrom(input, _repeated_alerts_codec);
            break;
          }
          case 88: {
            PendingEventCount = input.ReadInt64();
            break;
          }
          case 97: {
            PendingRate = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 16: {
            Client = (global::Google.Ads.GoogleAds.V21.Enums.OfflineEventUploadClientEnum.Types.OfflineEventUploadClient) input.ReadEnum();
            break;
          }
          case 24: {
            Status = (global::Google.Ads.GoogleAds.V21.Enums.OfflineConversionDiagnosticStatusEnum.Types.OfflineConversionDiagnosticStatus) input.ReadEnum();
            break;
          }
          case 32: {
            TotalEventCount = input.ReadInt64();
            break;
          }
          case 40: {
            SuccessfulEventCount = input.ReadInt64();
            break;
          }
          case 49: {
            SuccessRate = input.ReadDouble();
            break;
          }
          case 58: {
            LastUploadDateTime = input.ReadString();
            break;
          }
          case 66: {
            dailySummaries_.AddEntriesFrom(ref input, _repeated_dailySummaries_codec);
            break;
          }
          case 74: {
            jobSummaries_.AddEntriesFrom(ref input, _repeated_jobSummaries_codec);
            break;
          }
          case 82: {
            alerts_.AddEntriesFrom(ref input, _repeated_alerts_codec);
            break;
          }
          case 88: {
            PendingEventCount = input.ReadInt64();
            break;
          }
          case 97: {
            PendingRate = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Historical upload summary, grouped by upload date or job.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OfflineConversionSummary : pb::IMessage<OfflineConversionSummary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OfflineConversionSummary> _parser = new pb::MessageParser<OfflineConversionSummary>(() => new OfflineConversionSummary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OfflineConversionSummary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummaryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionSummary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionSummary(OfflineConversionSummary other) : this() {
      successfulCount_ = other.successfulCount_;
      failedCount_ = other.failedCount_;
      pendingCount_ = other.pendingCount_;
      switch (other.DimensionKeyCase) {
        case DimensionKeyOneofCase.JobId:
          JobId = other.JobId;
          break;
        case DimensionKeyOneofCase.UploadDate:
          UploadDate = other.UploadDate;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionSummary Clone() {
      return new OfflineConversionSummary(this);
    }

    /// <summary>Field number for the "successful_count" field.</summary>
    public const int SuccessfulCountFieldNumber = 3;
    private long successfulCount_;
    /// <summary>
    /// Output only. Total count of successful event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SuccessfulCount {
      get { return successfulCount_; }
      set {
        successfulCount_ = value;
      }
    }

    /// <summary>Field number for the "failed_count" field.</summary>
    public const int FailedCountFieldNumber = 4;
    private long failedCount_;
    /// <summary>
    /// Output only. Total count of failed event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FailedCount {
      get { return failedCount_; }
      set {
        failedCount_ = value;
      }
    }

    /// <summary>Field number for the "pending_count" field.</summary>
    public const int PendingCountFieldNumber = 5;
    private long pendingCount_;
    /// <summary>
    /// Output only. Total count of pending uploaded event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PendingCount {
      get { return pendingCount_; }
      set {
        pendingCount_ = value;
      }
    }

    /// <summary>Field number for the "job_id" field.</summary>
    public const int JobIdFieldNumber = 1;
    /// <summary>
    /// Output only. Dimension key for last N jobs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long JobId {
      get { return HasJobId ? (long) dimensionKey_ : 0L; }
      set {
        dimensionKey_ = value;
        dimensionKeyCase_ = DimensionKeyOneofCase.JobId;
      }
    }
    /// <summary>Gets whether the "job_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasJobId {
      get { return dimensionKeyCase_ == DimensionKeyOneofCase.JobId; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "job_id" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearJobId() {
      if (HasJobId) {
        ClearDimensionKey();
      }
    }

    /// <summary>Field number for the "upload_date" field.</summary>
    public const int UploadDateFieldNumber = 2;
    /// <summary>
    /// Output only. Dimension key for last N days.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UploadDate {
      get { return HasUploadDate ? (string) dimensionKey_ : ""; }
      set {
        dimensionKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dimensionKeyCase_ = DimensionKeyOneofCase.UploadDate;
      }
    }
    /// <summary>Gets whether the "upload_date" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUploadDate {
      get { return dimensionKeyCase_ == DimensionKeyOneofCase.UploadDate; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "upload_date" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUploadDate() {
      if (HasUploadDate) {
        ClearDimensionKey();
      }
    }

    private object dimensionKey_;
    /// <summary>Enum of possible cases for the "dimension_key" oneof.</summary>
    public enum DimensionKeyOneofCase {
      None = 0,
      JobId = 1,
      UploadDate = 2,
    }
    private DimensionKeyOneofCase dimensionKeyCase_ = DimensionKeyOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DimensionKeyOneofCase DimensionKeyCase {
      get { return dimensionKeyCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDimensionKey() {
      dimensionKeyCase_ = DimensionKeyOneofCase.None;
      dimensionKey_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OfflineConversionSummary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OfflineConversionSummary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SuccessfulCount != other.SuccessfulCount) return false;
      if (FailedCount != other.FailedCount) return false;
      if (PendingCount != other.PendingCount) return false;
      if (JobId != other.JobId) return false;
      if (UploadDate != other.UploadDate) return false;
      if (DimensionKeyCase != other.DimensionKeyCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SuccessfulCount != 0L) hash ^= SuccessfulCount.GetHashCode();
      if (FailedCount != 0L) hash ^= FailedCount.GetHashCode();
      if (PendingCount != 0L) hash ^= PendingCount.GetHashCode();
      if (HasJobId) hash ^= JobId.GetHashCode();
      if (HasUploadDate) hash ^= UploadDate.GetHashCode();
      hash ^= (int) dimensionKeyCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasJobId) {
        output.WriteRawTag(8);
        output.WriteInt64(JobId);
      }
      if (HasUploadDate) {
        output.WriteRawTag(18);
        output.WriteString(UploadDate);
      }
      if (SuccessfulCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SuccessfulCount);
      }
      if (FailedCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FailedCount);
      }
      if (PendingCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PendingCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasJobId) {
        output.WriteRawTag(8);
        output.WriteInt64(JobId);
      }
      if (HasUploadDate) {
        output.WriteRawTag(18);
        output.WriteString(UploadDate);
      }
      if (SuccessfulCount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(SuccessfulCount);
      }
      if (FailedCount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(FailedCount);
      }
      if (PendingCount != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(PendingCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SuccessfulCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SuccessfulCount);
      }
      if (FailedCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FailedCount);
      }
      if (PendingCount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PendingCount);
      }
      if (HasJobId) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(JobId);
      }
      if (HasUploadDate) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UploadDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OfflineConversionSummary other) {
      if (other == null) {
        return;
      }
      if (other.SuccessfulCount != 0L) {
        SuccessfulCount = other.SuccessfulCount;
      }
      if (other.FailedCount != 0L) {
        FailedCount = other.FailedCount;
      }
      if (other.PendingCount != 0L) {
        PendingCount = other.PendingCount;
      }
      switch (other.DimensionKeyCase) {
        case DimensionKeyOneofCase.JobId:
          JobId = other.JobId;
          break;
        case DimensionKeyOneofCase.UploadDate:
          UploadDate = other.UploadDate;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            JobId = input.ReadInt64();
            break;
          }
          case 18: {
            UploadDate = input.ReadString();
            break;
          }
          case 24: {
            SuccessfulCount = input.ReadInt64();
            break;
          }
          case 32: {
            FailedCount = input.ReadInt64();
            break;
          }
          case 40: {
            PendingCount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            JobId = input.ReadInt64();
            break;
          }
          case 18: {
            UploadDate = input.ReadString();
            break;
          }
          case 24: {
            SuccessfulCount = input.ReadInt64();
            break;
          }
          case 32: {
            FailedCount = input.ReadInt64();
            break;
          }
          case 40: {
            PendingCount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Alert for offline conversion client summary.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OfflineConversionAlert : pb::IMessage<OfflineConversionAlert>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OfflineConversionAlert> _parser = new pb::MessageParser<OfflineConversionAlert>(() => new OfflineConversionAlert());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OfflineConversionAlert> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummaryReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionAlert() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionAlert(OfflineConversionAlert other) : this() {
      error_ = other.error_ != null ? other.error_.Clone() : null;
      errorPercentage_ = other.errorPercentage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionAlert Clone() {
      return new OfflineConversionAlert(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError error_;
    /// <summary>
    /// Output only. Error for offline conversion client alert.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "error_percentage" field.</summary>
    public const int ErrorPercentageFieldNumber = 2;
    private double errorPercentage_;
    /// <summary>
    /// Output only. Percentage of the error, the range of this field should be
    /// [0, 1.0].
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double ErrorPercentage {
      get { return errorPercentage_; }
      set {
        errorPercentage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OfflineConversionAlert);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OfflineConversionAlert other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Error, other.Error)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ErrorPercentage, other.ErrorPercentage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (error_ != null) hash ^= Error.GetHashCode();
      if (ErrorPercentage != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ErrorPercentage);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (ErrorPercentage != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(ErrorPercentage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (error_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Error);
      }
      if (ErrorPercentage != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(ErrorPercentage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (error_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Error);
      }
      if (ErrorPercentage != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OfflineConversionAlert other) {
      if (other == null) {
        return;
      }
      if (other.error_ != null) {
        if (error_ == null) {
          Error = new global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError();
        }
        Error.MergeFrom(other.Error);
      }
      if (other.ErrorPercentage != 0D) {
        ErrorPercentage = other.ErrorPercentage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError();
            }
            input.ReadMessage(Error);
            break;
          }
          case 17: {
            ErrorPercentage = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (error_ == null) {
              Error = new global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionError();
            }
            input.ReadMessage(Error);
            break;
          }
          case 17: {
            ErrorPercentage = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Possible errors for offline conversion client summary.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OfflineConversionError : pb::IMessage<OfflineConversionError>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OfflineConversionError> _parser = new pb::MessageParser<OfflineConversionError>(() => new OfflineConversionError());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OfflineConversionError> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V21.Resources.OfflineConversionUploadClientSummaryReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionError() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionError(OfflineConversionError other) : this() {
      switch (other.ErrorCodeCase) {
        case ErrorCodeOneofCase.CollectionSizeError:
          CollectionSizeError = other.CollectionSizeError;
          break;
        case ErrorCodeOneofCase.ConversionAdjustmentUploadError:
          ConversionAdjustmentUploadError = other.ConversionAdjustmentUploadError;
          break;
        case ErrorCodeOneofCase.ConversionUploadError:
          ConversionUploadError = other.ConversionUploadError;
          break;
        case ErrorCodeOneofCase.DateError:
          DateError = other.DateError;
          break;
        case ErrorCodeOneofCase.DistinctError:
          DistinctError = other.DistinctError;
          break;
        case ErrorCodeOneofCase.FieldError:
          FieldError = other.FieldError;
          break;
        case ErrorCodeOneofCase.MutateError:
          MutateError = other.MutateError;
          break;
        case ErrorCodeOneofCase.NotAllowlistedError:
          NotAllowlistedError = other.NotAllowlistedError;
          break;
        case ErrorCodeOneofCase.StringFormatError:
          StringFormatError = other.StringFormatError;
          break;
        case ErrorCodeOneofCase.StringLengthError:
          StringLengthError = other.StringLengthError;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OfflineConversionError Clone() {
      return new OfflineConversionError(this);
    }

    /// <summary>Field number for the "collection_size_error" field.</summary>
    public const int CollectionSizeErrorFieldNumber = 1;
    /// <summary>
    /// Output only. Collection size error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.CollectionSizeErrorEnum.Types.CollectionSizeError CollectionSizeError {
      get { return HasCollectionSizeError ? (global::Google.Ads.GoogleAds.V21.Errors.CollectionSizeErrorEnum.Types.CollectionSizeError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.CollectionSizeErrorEnum.Types.CollectionSizeError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.CollectionSizeError;
      }
    }
    /// <summary>Gets whether the "collection_size_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCollectionSizeError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.CollectionSizeError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "collection_size_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCollectionSizeError() {
      if (HasCollectionSizeError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "conversion_adjustment_upload_error" field.</summary>
    public const int ConversionAdjustmentUploadErrorFieldNumber = 2;
    /// <summary>
    /// Output only. Conversion adjustment upload error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.ConversionAdjustmentUploadErrorEnum.Types.ConversionAdjustmentUploadError ConversionAdjustmentUploadError {
      get { return HasConversionAdjustmentUploadError ? (global::Google.Ads.GoogleAds.V21.Errors.ConversionAdjustmentUploadErrorEnum.Types.ConversionAdjustmentUploadError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.ConversionAdjustmentUploadErrorEnum.Types.ConversionAdjustmentUploadError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.ConversionAdjustmentUploadError;
      }
    }
    /// <summary>Gets whether the "conversion_adjustment_upload_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConversionAdjustmentUploadError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.ConversionAdjustmentUploadError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "conversion_adjustment_upload_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConversionAdjustmentUploadError() {
      if (HasConversionAdjustmentUploadError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "conversion_upload_error" field.</summary>
    public const int ConversionUploadErrorFieldNumber = 3;
    /// <summary>
    /// Output only. Conversion upload error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.ConversionUploadErrorEnum.Types.ConversionUploadError ConversionUploadError {
      get { return HasConversionUploadError ? (global::Google.Ads.GoogleAds.V21.Errors.ConversionUploadErrorEnum.Types.ConversionUploadError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.ConversionUploadErrorEnum.Types.ConversionUploadError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.ConversionUploadError;
      }
    }
    /// <summary>Gets whether the "conversion_upload_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConversionUploadError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.ConversionUploadError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "conversion_upload_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConversionUploadError() {
      if (HasConversionUploadError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "date_error" field.</summary>
    public const int DateErrorFieldNumber = 4;
    /// <summary>
    /// Output only. Date error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.DateErrorEnum.Types.DateError DateError {
      get { return HasDateError ? (global::Google.Ads.GoogleAds.V21.Errors.DateErrorEnum.Types.DateError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.DateErrorEnum.Types.DateError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.DateError;
      }
    }
    /// <summary>Gets whether the "date_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDateError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.DateError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "date_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDateError() {
      if (HasDateError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "distinct_error" field.</summary>
    public const int DistinctErrorFieldNumber = 5;
    /// <summary>
    /// Output only. Distinct error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.DistinctErrorEnum.Types.DistinctError DistinctError {
      get { return HasDistinctError ? (global::Google.Ads.GoogleAds.V21.Errors.DistinctErrorEnum.Types.DistinctError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.DistinctErrorEnum.Types.DistinctError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.DistinctError;
      }
    }
    /// <summary>Gets whether the "distinct_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDistinctError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.DistinctError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "distinct_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDistinctError() {
      if (HasDistinctError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "field_error" field.</summary>
    public const int FieldErrorFieldNumber = 6;
    /// <summary>
    /// Output only. Field error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.FieldErrorEnum.Types.FieldError FieldError {
      get { return HasFieldError ? (global::Google.Ads.GoogleAds.V21.Errors.FieldErrorEnum.Types.FieldError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.FieldErrorEnum.Types.FieldError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.FieldError;
      }
    }
    /// <summary>Gets whether the "field_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFieldError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.FieldError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "field_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFieldError() {
      if (HasFieldError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "mutate_error" field.</summary>
    public const int MutateErrorFieldNumber = 7;
    /// <summary>
    /// Output only. Mutate error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.MutateErrorEnum.Types.MutateError MutateError {
      get { return HasMutateError ? (global::Google.Ads.GoogleAds.V21.Errors.MutateErrorEnum.Types.MutateError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.MutateErrorEnum.Types.MutateError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.MutateError;
      }
    }
    /// <summary>Gets whether the "mutate_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMutateError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.MutateError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "mutate_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMutateError() {
      if (HasMutateError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "not_allowlisted_error" field.</summary>
    public const int NotAllowlistedErrorFieldNumber = 8;
    /// <summary>
    /// Output only. Not allowlisted error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.NotAllowlistedErrorEnum.Types.NotAllowlistedError NotAllowlistedError {
      get { return HasNotAllowlistedError ? (global::Google.Ads.GoogleAds.V21.Errors.NotAllowlistedErrorEnum.Types.NotAllowlistedError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.NotAllowlistedErrorEnum.Types.NotAllowlistedError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.NotAllowlistedError;
      }
    }
    /// <summary>Gets whether the "not_allowlisted_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasNotAllowlistedError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.NotAllowlistedError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "not_allowlisted_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearNotAllowlistedError() {
      if (HasNotAllowlistedError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "string_format_error" field.</summary>
    public const int StringFormatErrorFieldNumber = 9;
    /// <summary>
    /// Output only. String format error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.StringFormatErrorEnum.Types.StringFormatError StringFormatError {
      get { return HasStringFormatError ? (global::Google.Ads.GoogleAds.V21.Errors.StringFormatErrorEnum.Types.StringFormatError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.StringFormatErrorEnum.Types.StringFormatError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.StringFormatError;
      }
    }
    /// <summary>Gets whether the "string_format_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringFormatError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.StringFormatError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "string_format_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringFormatError() {
      if (HasStringFormatError) {
        ClearErrorCode();
      }
    }

    /// <summary>Field number for the "string_length_error" field.</summary>
    public const int StringLengthErrorFieldNumber = 10;
    /// <summary>
    /// Output only. String length error.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Ads.GoogleAds.V21.Errors.StringLengthErrorEnum.Types.StringLengthError StringLengthError {
      get { return HasStringLengthError ? (global::Google.Ads.GoogleAds.V21.Errors.StringLengthErrorEnum.Types.StringLengthError) errorCode_ : global::Google.Ads.GoogleAds.V21.Errors.StringLengthErrorEnum.Types.StringLengthError.Unspecified; }
      set {
        errorCode_ = value;
        errorCodeCase_ = ErrorCodeOneofCase.StringLengthError;
      }
    }
    /// <summary>Gets whether the "string_length_error" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasStringLengthError {
      get { return errorCodeCase_ == ErrorCodeOneofCase.StringLengthError; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "string_length_error" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStringLengthError() {
      if (HasStringLengthError) {
        ClearErrorCode();
      }
    }

    private object errorCode_;
    /// <summary>Enum of possible cases for the "error_code" oneof.</summary>
    public enum ErrorCodeOneofCase {
      None = 0,
      CollectionSizeError = 1,
      ConversionAdjustmentUploadError = 2,
      ConversionUploadError = 3,
      DateError = 4,
      DistinctError = 5,
      FieldError = 6,
      MutateError = 7,
      NotAllowlistedError = 8,
      StringFormatError = 9,
      StringLengthError = 10,
    }
    private ErrorCodeOneofCase errorCodeCase_ = ErrorCodeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ErrorCodeOneofCase ErrorCodeCase {
      get { return errorCodeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearErrorCode() {
      errorCodeCase_ = ErrorCodeOneofCase.None;
      errorCode_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OfflineConversionError);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OfflineConversionError other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CollectionSizeError != other.CollectionSizeError) return false;
      if (ConversionAdjustmentUploadError != other.ConversionAdjustmentUploadError) return false;
      if (ConversionUploadError != other.ConversionUploadError) return false;
      if (DateError != other.DateError) return false;
      if (DistinctError != other.DistinctError) return false;
      if (FieldError != other.FieldError) return false;
      if (MutateError != other.MutateError) return false;
      if (NotAllowlistedError != other.NotAllowlistedError) return false;
      if (StringFormatError != other.StringFormatError) return false;
      if (StringLengthError != other.StringLengthError) return false;
      if (ErrorCodeCase != other.ErrorCodeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCollectionSizeError) hash ^= CollectionSizeError.GetHashCode();
      if (HasConversionAdjustmentUploadError) hash ^= ConversionAdjustmentUploadError.GetHashCode();
      if (HasConversionUploadError) hash ^= ConversionUploadError.GetHashCode();
      if (HasDateError) hash ^= DateError.GetHashCode();
      if (HasDistinctError) hash ^= DistinctError.GetHashCode();
      if (HasFieldError) hash ^= FieldError.GetHashCode();
      if (HasMutateError) hash ^= MutateError.GetHashCode();
      if (HasNotAllowlistedError) hash ^= NotAllowlistedError.GetHashCode();
      if (HasStringFormatError) hash ^= StringFormatError.GetHashCode();
      if (HasStringLengthError) hash ^= StringLengthError.GetHashCode();
      hash ^= (int) errorCodeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCollectionSizeError) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CollectionSizeError);
      }
      if (HasConversionAdjustmentUploadError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ConversionAdjustmentUploadError);
      }
      if (HasConversionUploadError) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ConversionUploadError);
      }
      if (HasDateError) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DateError);
      }
      if (HasDistinctError) {
        output.WriteRawTag(40);
        output.WriteEnum((int) DistinctError);
      }
      if (HasFieldError) {
        output.WriteRawTag(48);
        output.WriteEnum((int) FieldError);
      }
      if (HasMutateError) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MutateError);
      }
      if (HasNotAllowlistedError) {
        output.WriteRawTag(64);
        output.WriteEnum((int) NotAllowlistedError);
      }
      if (HasStringFormatError) {
        output.WriteRawTag(72);
        output.WriteEnum((int) StringFormatError);
      }
      if (HasStringLengthError) {
        output.WriteRawTag(80);
        output.WriteEnum((int) StringLengthError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCollectionSizeError) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CollectionSizeError);
      }
      if (HasConversionAdjustmentUploadError) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ConversionAdjustmentUploadError);
      }
      if (HasConversionUploadError) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ConversionUploadError);
      }
      if (HasDateError) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DateError);
      }
      if (HasDistinctError) {
        output.WriteRawTag(40);
        output.WriteEnum((int) DistinctError);
      }
      if (HasFieldError) {
        output.WriteRawTag(48);
        output.WriteEnum((int) FieldError);
      }
      if (HasMutateError) {
        output.WriteRawTag(56);
        output.WriteEnum((int) MutateError);
      }
      if (HasNotAllowlistedError) {
        output.WriteRawTag(64);
        output.WriteEnum((int) NotAllowlistedError);
      }
      if (HasStringFormatError) {
        output.WriteRawTag(72);
        output.WriteEnum((int) StringFormatError);
      }
      if (HasStringLengthError) {
        output.WriteRawTag(80);
        output.WriteEnum((int) StringLengthError);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCollectionSizeError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CollectionSizeError);
      }
      if (HasConversionAdjustmentUploadError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ConversionAdjustmentUploadError);
      }
      if (HasConversionUploadError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ConversionUploadError);
      }
      if (HasDateError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DateError);
      }
      if (HasDistinctError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DistinctError);
      }
      if (HasFieldError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FieldError);
      }
      if (HasMutateError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MutateError);
      }
      if (HasNotAllowlistedError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NotAllowlistedError);
      }
      if (HasStringFormatError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StringFormatError);
      }
      if (HasStringLengthError) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) StringLengthError);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OfflineConversionError other) {
      if (other == null) {
        return;
      }
      switch (other.ErrorCodeCase) {
        case ErrorCodeOneofCase.CollectionSizeError:
          CollectionSizeError = other.CollectionSizeError;
          break;
        case ErrorCodeOneofCase.ConversionAdjustmentUploadError:
          ConversionAdjustmentUploadError = other.ConversionAdjustmentUploadError;
          break;
        case ErrorCodeOneofCase.ConversionUploadError:
          ConversionUploadError = other.ConversionUploadError;
          break;
        case ErrorCodeOneofCase.DateError:
          DateError = other.DateError;
          break;
        case ErrorCodeOneofCase.DistinctError:
          DistinctError = other.DistinctError;
          break;
        case ErrorCodeOneofCase.FieldError:
          FieldError = other.FieldError;
          break;
        case ErrorCodeOneofCase.MutateError:
          MutateError = other.MutateError;
          break;
        case ErrorCodeOneofCase.NotAllowlistedError:
          NotAllowlistedError = other.NotAllowlistedError;
          break;
        case ErrorCodeOneofCase.StringFormatError:
          StringFormatError = other.StringFormatError;
          break;
        case ErrorCodeOneofCase.StringLengthError:
          StringLengthError = other.StringLengthError;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.CollectionSizeError;
            break;
          }
          case 16: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.ConversionAdjustmentUploadError;
            break;
          }
          case 24: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.ConversionUploadError;
            break;
          }
          case 32: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.DateError;
            break;
          }
          case 40: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.DistinctError;
            break;
          }
          case 48: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.FieldError;
            break;
          }
          case 56: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.MutateError;
            break;
          }
          case 64: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.NotAllowlistedError;
            break;
          }
          case 72: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.StringFormatError;
            break;
          }
          case 80: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.StringLengthError;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.CollectionSizeError;
            break;
          }
          case 16: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.ConversionAdjustmentUploadError;
            break;
          }
          case 24: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.ConversionUploadError;
            break;
          }
          case 32: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.DateError;
            break;
          }
          case 40: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.DistinctError;
            break;
          }
          case 48: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.FieldError;
            break;
          }
          case 56: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.MutateError;
            break;
          }
          case 64: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.NotAllowlistedError;
            break;
          }
          case 72: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.StringFormatError;
            break;
          }
          case 80: {
            errorCode_ = input.ReadEnum();
            errorCodeCase_ = ErrorCodeOneofCase.StringLengthError;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
