// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/ads/googleads/v19/resources/ad_group_ad_asset_combination_view.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Ads.GoogleAds.V19.Resources {

  /// <summary>Holder for reflection information generated from google/ads/googleads/v19/resources/ad_group_ad_asset_combination_view.proto</summary>
  public static partial class AdGroupAdAssetCombinationViewReflection {

    #region Descriptor
    /// <summary>File descriptor for google/ads/googleads/v19/resources/ad_group_ad_asset_combination_view.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdGroupAdAssetCombinationViewReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cktnb29nbGUvYWRzL2dvb2dsZWFkcy92MTkvcmVzb3VyY2VzL2FkX2dyb3Vw",
            "X2FkX2Fzc2V0X2NvbWJpbmF0aW9uX3ZpZXcucHJvdG8SImdvb2dsZS5hZHMu",
            "Z29vZ2xlYWRzLnYxOS5yZXNvdXJjZXMaMWdvb2dsZS9hZHMvZ29vZ2xlYWRz",
            "L3YxOS9jb21tb24vYXNzZXRfdXNhZ2UucHJvdG8aH2dvb2dsZS9hcGkvZmll",
            "bGRfYmVoYXZpb3IucHJvdG8aGWdvb2dsZS9hcGkvcmVzb3VyY2UucHJvdG8i",
            "qwMKHUFkR3JvdXBBZEFzc2V0Q29tYmluYXRpb25WaWV3ElUKDXJlc291cmNl",
            "X25hbWUYASABKAlCPuBBA/pBOAo2Z29vZ2xlYWRzLmdvb2dsZWFwaXMuY29t",
            "L0FkR3JvdXBBZEFzc2V0Q29tYmluYXRpb25WaWV3EkcKDXNlcnZlZF9hc3Nl",
            "dHMYAiADKAsyKy5nb29nbGUuYWRzLmdvb2dsZWFkcy52MTkuY29tbW9uLkFz",
            "c2V0VXNhZ2VCA+BBAxIZCgdlbmFibGVkGAMgASgIQgPgQQNIAIgBATrCAepB",
            "vgEKNmdvb2dsZWFkcy5nb29nbGVhcGlzLmNvbS9BZEdyb3VwQWRBc3NldENv",
            "bWJpbmF0aW9uVmlldxKDAWN1c3RvbWVycy97Y3VzdG9tZXJfaWR9L2FkR3Jv",
            "dXBBZEFzc2V0Q29tYmluYXRpb25WaWV3cy97YWRfZ3JvdXBfaWR9fnthZF9p",
            "ZH1+e2Fzc2V0X2NvbWJpbmF0aW9uX2lkX2xvd31+e2Fzc2V0X2NvbWJpbmF0",
            "aW9uX2lkX2hpZ2h9QgoKCF9lbmFibGVkQpQCCiZjb20uZ29vZ2xlLmFkcy5n",
            "b29nbGVhZHMudjE5LnJlc291cmNlc0IiQWRHcm91cEFkQXNzZXRDb21iaW5h",
            "dGlvblZpZXdQcm90b1ABWktnb29nbGUuZ29sYW5nLm9yZy9nZW5wcm90by9n",
            "b29nbGVhcGlzL2Fkcy9nb29nbGVhZHMvdjE5L3Jlc291cmNlcztyZXNvdXJj",
            "ZXOiAgNHQUGqAiJHb29nbGUuQWRzLkdvb2dsZUFkcy5WMTkuUmVzb3VyY2Vz",
            "ygIiR29vZ2xlXEFkc1xHb29nbGVBZHNcVjE5XFJlc291cmNlc+oCJkdvb2ds",
            "ZTo6QWRzOjpHb29nbGVBZHM6OlYxOTo6UmVzb3VyY2VzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Ads.GoogleAds.V19.Common.AssetUsageReflection.Descriptor, global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Api.ResourceReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Ads.GoogleAds.V19.Resources.AdGroupAdAssetCombinationView), global::Google.Ads.GoogleAds.V19.Resources.AdGroupAdAssetCombinationView.Parser, new[]{ "ResourceName", "ServedAssets", "Enabled" }, new[]{ "Enabled" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// A view on the usage of ad group ad asset combination.
  /// Now we only support AdGroupAdAssetCombinationView for Responsive Search Ads,
  /// with more ad types planned for the future.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AdGroupAdAssetCombinationView : pb::IMessage<AdGroupAdAssetCombinationView>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AdGroupAdAssetCombinationView> _parser = new pb::MessageParser<AdGroupAdAssetCombinationView>(() => new AdGroupAdAssetCombinationView());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AdGroupAdAssetCombinationView> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Ads.GoogleAds.V19.Resources.AdGroupAdAssetCombinationViewReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdGroupAdAssetCombinationView() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdGroupAdAssetCombinationView(AdGroupAdAssetCombinationView other) : this() {
      _hasBits0 = other._hasBits0;
      resourceName_ = other.resourceName_;
      servedAssets_ = other.servedAssets_.Clone();
      enabled_ = other.enabled_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AdGroupAdAssetCombinationView Clone() {
      return new AdGroupAdAssetCombinationView(this);
    }

    /// <summary>Field number for the "resource_name" field.</summary>
    public const int ResourceNameFieldNumber = 1;
    private string resourceName_ = "";
    /// <summary>
    /// Output only. The resource name of the ad group ad asset combination view.
    /// The combination ID is 128 bits long, where the upper 64 bits are stored in
    /// asset_combination_id_high, and the lower 64 bits are stored in
    /// asset_combination_id_low.
    /// AdGroupAd Asset Combination view resource names have the form:
    /// `customers/{customer_id}/adGroupAdAssetCombinationViews/{AdGroupAd.ad_group_id}~{AdGroupAd.ad.ad_id}~{AssetCombination.asset_combination_id_low}~{AssetCombination.asset_combination_id_high}`
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ResourceName {
      get { return resourceName_; }
      set {
        resourceName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "served_assets" field.</summary>
    public const int ServedAssetsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Ads.GoogleAds.V19.Common.AssetUsage> _repeated_servedAssets_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Ads.GoogleAds.V19.Common.AssetUsage.Parser);
    private readonly pbc::RepeatedField<global::Google.Ads.GoogleAds.V19.Common.AssetUsage> servedAssets_ = new pbc::RepeatedField<global::Google.Ads.GoogleAds.V19.Common.AssetUsage>();
    /// <summary>
    /// Output only. Served assets.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Ads.GoogleAds.V19.Common.AssetUsage> ServedAssets {
      get { return servedAssets_; }
    }

    /// <summary>Field number for the "enabled" field.</summary>
    public const int EnabledFieldNumber = 3;
    private readonly static bool EnabledDefaultValue = false;

    private bool enabled_;
    /// <summary>
    /// Output only. The status between the asset combination and the latest
    /// version of the ad. If true, the asset combination is linked to the latest
    /// version of the ad. If false, it means the link once existed but has been
    /// removed and is no longer present in the latest version of the ad.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Enabled {
      get { if ((_hasBits0 & 1) != 0) { return enabled_; } else { return EnabledDefaultValue; } }
      set {
        _hasBits0 |= 1;
        enabled_ = value;
      }
    }
    /// <summary>Gets whether the "enabled" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEnabled {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "enabled" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEnabled() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AdGroupAdAssetCombinationView);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AdGroupAdAssetCombinationView other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResourceName != other.ResourceName) return false;
      if(!servedAssets_.Equals(other.servedAssets_)) return false;
      if (Enabled != other.Enabled) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ResourceName.Length != 0) hash ^= ResourceName.GetHashCode();
      hash ^= servedAssets_.GetHashCode();
      if (HasEnabled) hash ^= Enabled.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      servedAssets_.WriteTo(output, _repeated_servedAssets_codec);
      if (HasEnabled) {
        output.WriteRawTag(24);
        output.WriteBool(Enabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ResourceName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResourceName);
      }
      servedAssets_.WriteTo(ref output, _repeated_servedAssets_codec);
      if (HasEnabled) {
        output.WriteRawTag(24);
        output.WriteBool(Enabled);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ResourceName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResourceName);
      }
      size += servedAssets_.CalculateSize(_repeated_servedAssets_codec);
      if (HasEnabled) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AdGroupAdAssetCombinationView other) {
      if (other == null) {
        return;
      }
      if (other.ResourceName.Length != 0) {
        ResourceName = other.ResourceName;
      }
      servedAssets_.Add(other.servedAssets_);
      if (other.HasEnabled) {
        Enabled = other.Enabled;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 18: {
            servedAssets_.AddEntriesFrom(input, _repeated_servedAssets_codec);
            break;
          }
          case 24: {
            Enabled = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ResourceName = input.ReadString();
            break;
          }
          case 18: {
            servedAssets_.AddEntriesFrom(ref input, _repeated_servedAssets_codec);
            break;
          }
          case 24: {
            Enabled = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
