name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Build and pack
      run: dotnet pack -c Release -p:PackagePath=Google.Ads.GoogleAds.Extensions.DependencyInjection

    - name: Publish NuGet package
      run: dotnet nuget push -s https://nuget.nwcloudsolutions.com/v3/index.json -k ${{ secrets.NUGET_API_KEY }} **/*.nupkg